eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    instance:
      hostname: localhost

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://userService
          predicates:
            - Path=/user/**

        - id: product
          uri: lb://productService
          predicates:
            - Path=/product/**